version: "3.2"

services:
  assessment-person-api:
    image: assessment-person-api
    build:
     context: .
     dockerfile: AssessmentPersonAPI/Dockerfile
     args:
     - LBHPACKAGESTOKEN=${LBHPACKAGESTOKEN}
    ports:
      - 5000:5000

  assessment-person-api-test:
    image: assessment-person-api-test
    build:
      context: .
      dockerfile: AssessmentPersonAPI.Tests/Dockerfile
      args:
      - LBHPACKAGESTOKEN=${LBHPACKAGESTOKEN}
